export const ActionTypes = {
    SET_PRODUCTS: 'SET_PRODUCTS',
    ADD_PRODUCT: 'ADD_PRODUCT',
    REMOVE_PRODUCT: 'REMOVE_PRODUCT',
    UPDATE_PRODUCT_STOCK: 'UPDATE_PRODUCT_STOCK',
    UPDATE_PRODUCT_DETAILS: 'UPDATE_PRODUCT_DETAILS',
  };
 
  